# Generated by Django 4.2.1 on 2023-05-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoMaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typee",
                    models.CharField(
                        choices=[
                            ("vo", "voice over"),
                            ("bg_music", "backgournd music"),
                            ("video_music", "vidio music"),
                        ],
                        max_length=15,
                    ),
                ),
                ("high_volume", models.PositiveIntegerField()),
                ("low_volume", models.PositiveIntegerField()),
                (
                    "video_component_id",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("start_time", models.PositiveIntegerField(blank=True, null=True)),
                ("end_time", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
